Vagrant.configure("2") do |config|

  config.vm.define "centos6" do |centos6|
    centos6.vm.box = "centos6-base"
    centos6.vm.hostname = "centos6"
    #centos6.vm.network "private_network", ip: "192.128.10.100"
    centos6.vm.network "public_network"
  end

  #config.vm.provision "ansible_local" do |ansible|
  #  ansible.playbook = "provision/common.yml"
  #end
  
end
