Vagrant.configure("2") do |config|

  config.vm.define "repo" do |repo|
    repo.vm.box = "centos7-base"
    repo.vm.hostname = "repo"
    repo.vm.network "private_network", ip: "192.128.10.11"
  end

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "provision/common.yml"
  end
  
end
