Vagrant.configure("2") do |config|

  config.vm.define "node1" do |node1|
    node1.vm.box = "centos7-base"
    node1.vm.hostname = "node1"
    node1.vm.network "private_network", ip: "192.128.10.10"
  end

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "provision/common.yml"
  end
  
end
