Vagrant.configure("2") do |config|

  config.vm.define "centos7-non-updated" do |repo|
    repo.vm.box = "centos7-non-updated"
    repo.vm.hostname = "centos7-non-updated"
    repo.vm.network "private_network", ip: "192.128.10.19"
  end
  
end
