Vagrant.configure("2") do |config|
  config.vm.box = "centos7-base"
  config.vm.hostname = "ansible"
  config.vm.network "private_network", ip: "192.168.1.1",
    virtualbox__intnet: true
  config.vm.provider "virtualbox" do |v|
    v.memory = 1560
    v.cpus = 2

#  config.vm.provision "ansible" do |ansible|
#    ansible.playbook = "ansible.yml"
#  end
end
